ALTER TABLE `users` ADD COLUMN `lastLoginIp` VARCHAR(45) NULL;
ALTER TABLE `users` ADD COLUMN `lastLoginUa` VARCHAR(500) NULL;
ALTER TABLE `users` ADD COLUMN `tokenVersion` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `maintenance_logs` ADD COLUMN `createdById` INTEGER NULL;